name: CI

on:
  push:
    branches: [ homework6 ]
  pull_request:
    branches: [ homework6 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: cd homework6 || env GOOS=linux GOARCH=386 go build -o file-duplicates-finder homework6/cmd/file-duplicates-finder/main.go

      - name: Test
        run: cd homework6 || go test -race ./... 
